name: 'cow_swap_analysis'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
  cow_swap_analysis:
    staging:
      +materialized: view
    marts:
      +materialized: table