default:
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      pass: airflow
      port: 5432
      dbname: airflow
      schema: public
      threads: 1
      keepalives_idle: 0
  target: dev